version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    ports:
      - 8080:8080

  db:
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
