version: '3'
services:
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    volumes:
      - .:/app
    tty: true
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    build:
      context: build/db
      dockerfile: Dockerfile
    volumes:
      - ./build/db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  cache:
    build:
      context: build/cache
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  proxy:
    image: nginx:1.25.4
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./build/proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
