openapi: '3.0.0'

info:
  version: "1.0.0"
  title: User-Register-API
  
tags:
  - name: user

paths:
  /:
    get:
      description: |
        接続確認用のエンドポイント

      responses:
        200:
          description: Successful responses
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Connect successfully"

  /signin:
    post:
      tags:
        - user
      description: |
        新しいユーザーを登録する

      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            required:
              - user_id
              - password
            properties:
              user_id:
                type: "string"
              username:
                type: "string"
              password:
                type: "string"

      responses:
        200:
          description: Successful responses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User created successfully"
                  user:
                    type: object
                    properties:
                      user_id:
                        type: string
                        example: "user_id"
                      username:
                        type: string
                        example: "username"
        400:
          description: リクエストの形式が正しくない場合や既に存在するユーザーIDの場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User already exists"

  /user/{user_id}: 
    get:
      tags:
        - user
      description: |
        ユーザー情報を取得する

      parameters:
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              password:
                type: "string"

      responses:
        200:
          description: Successful responses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User can be acquired"
                  user:
                    type: object
                    properties:
                      user_id:
                        type: string
                        example: "user_id"
                      username:
                        type: string
                        example: "username"
        400:
          description: パスワードが正しくない場合や存在しないユーザーIDの場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User does not exist"
    put:
      tags:
        - user
      description: |
        ユーザー情報を更新する

      parameters:
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"

      responses:
        200:
          description: Successful responses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User can be updated"
                  user:
                    type: object
                    properties:
                      user_id:
                        type: string
                        example: "user_id"
                      username:
                        type: string
                        example: "username"
        400:
          description: パスワードが正しくない場合や存在しないユーザーIDの場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User does not exist"

  /delete/{user_id}:
    delete:
      tags:
        - user
      description: |
        ユーザー情報を削除する
      
      parameters:
        - name: "user_id"
          in: "path"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              password:
                type: "string"
      
      responses:
        200:
          description: Successful responses
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User can be deleted"
        400:
          description: パスワードが正しくない場合や存在しないユーザーIDの場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User does not exist"