name: Run Go test
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go mod tidy
      - name: Run Server
        run: |
          nohup go run main.go &
          sleep 5
      - name: Test with the Go CLI
        run: go test
  
